### ISSUE TITLE
[SAP][Analytical Table] onSelectionChange gives wrong data

### ISSUE THREAD

**Issue by thisisjasmeet** [SAP/ui5-webcomponents-react#3612] opened 2022-10-04 11:53 UTC
!! It is needed for Internal SAP consumption !!

![image](https://user-images.githubusercontent.com/57886348/193810827-042d830d-0030-449d-b7b1-35e41fc849e8.png)

**Describe the bug**
onSelectionChange event has property selectedFlatRows

on checking for a parent node which has some unselected items
**isSomeSelected is coming as false.**

Expected behavior
**it should be true.**

UI5 Web Components for React Information
@ui5/webcomponents-react version: v 1.0.1
Operating System: macos
Browser: chrome

It is needed for Internal SAP consumption

**Comment by rit-clone** [comment] 2022-10-09 11:35
Hey @Lukas742. Can you please assign me the issue?

**Comment by Lukas742** [comment] 2022-10-10 06:17
Hi @rit-clone 

sure :) 
Thanks a lot for your support!

**Comment by rit-clone** [comment] 2022-10-10 11:28
@thisisjasmeet I am unable to recreate this bug in my system. Can you please elaborate on what it is that's not working and how to get to the buggy state?

**Comment by Lukas742** [comment] 2022-10-11 09:16
Hi @thisisjasmeet 

could you please add a reproducible example, preferably by using this [codeSandbox template](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34)?

**Comment by thisisjasmeet** [comment] 2022-10-12 04:09
> Hi @thisisjasmeet
> 
> could you please add a reproducible example, preferably by using this [codeSandbox template](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34)?

https://codesandbox.io/s/treetable-forked-sc3u19?file=/src/App.js

![image](https://user-images.githubusercontent.com/57886348/195247875-e4e06172-074b-4df6-b016-eb70c7324fdc.png)

**Comment by thisisjasmeet** [comment] 2022-10-17 06:27
@Lukas742 @rit-clone  by when we can have fix for this.

This is a critical thing that needs to be fixed.

Thanks in advance :)

**Comment by Lukas742** [comment] 2022-10-19 10:16
Hi @rit-clone

are you still looking into this issue and do you have a broad estimate for the fix? If your schedule is full and you can’t find the time to work on it, that’s no problem at all, just please let us know so we can take over.
Thanks again :)

**Comment by rit-clone** [comment] 2022-10-19 12:57
Hi @Lukas742 sorry for taking your time. This issue is quite tricky and I have prior deadlines from my organization. Can you please assign this to someone else?

**Comment by Lukas742** [comment] 2022-10-19 13:42
@rit-clone no problem and thanks for the response.

**Comment by thisisjasmeet** [comment] 2022-10-26 03:47
The issue is still occuring https://codesandbox.io/s/treetable-forked-sc3u19?file=/src/App.js


https://user-images.githubusercontent.com/57886348/197930025-6abf6ede-ad21-4a7e-b1d4-269b583185c3.mp4

**Comment by Lukas742** [comment] 2022-10-27 13:59
Hi @thisisjasmeet 

I realized just now what the actual issue is. At first I thought this was connected to the `selectedFlatRows` issue, but as it turns out this is an issue with the `useIndeterminateRowSelect` hook. As this is more complex it will unfortunately take some time to resolve this.

**Comment by Lukas742** [comment] 2022-11-23 12:15
Hi @thisisjasmeet 

unfortunately it's not practical for us changing `isSomeSelected` to show the desired value. 
The property is coming from the underlying library we use to construct our table and the value is not changed to `true` because the row is still selected and only `isSelected` or `isSomeSelected` can be true at the same time. 

When the second linked [PR](https://github.com/SAP/ui5-webcomponents-react/pull/3797) is merged, the plugin hook will allow passing a callback as parameter which is fired every time the internal indeterminate state is changed. Then you will be able to get all indeterminate rows via the event param.

**Closed** 2022-11-24 09:08 UTC
Labels: bug
