### ISSUE TITLE
VariantManagement: Variant Name Validation in the Save As Dialog is incorrectly working 

### ISSUE THREAD

**Issue by nidhi0104** [SAP/ui5-webcomponents-react#2941] opened 2022-05-12 16:27 UTC
The variant name validation in the save as dialog is not working correctly.For the first time it gives wrong message that 'a file with this name already exists' and on pressing the save button second time it saves the variant.

**To Reproduce**
1. Go to Variant Management. 
2. Click on Save As
3. Enter Unique Variant Name
4. Press Save Button

**Expected behavior**
If the variant name is unique, it should not give error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/105447668/168123039-3ce36396-df3a-43d7-9541-3e515f9ad811.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.2.3
`@ui5/webcomponents-react` version: 0.22.5
Operating System: M1
Browser: Chrome

**Additional context**

**Comment by Lukas742** [comment] 2022-05-12 17:14
Hi @nidhi0104 

this is a duplicate of https://github.com/SAP/ui5-webcomponents-react/issues/2877 and the fix will be available with our next release.

**Closed by Lukas742** 2022-05-12 17:14 UTC
Labels: bug
