### ISSUE TITLE
[ComboBox]: Change events are triggered with default value despite no change

### ISSUE THREAD

**Issue by lenafi5cher** [SAP/ui5-webcomponents-react#6254] opened 2024-08-23 08:42 UTC
### Describe the bug

If the combobox has the value property set to a value that matches the comboboxitem values, the onChange event will still be triggered, despite no change taking place. This only happens on first interaction.
Still the combobox  seems to recognize that the value matches one of the dropdown values, as it shows the item as selected when opening the dropdown.

``` 
<ComboBox
      icon={<Icon name="employee" />}
      onChange={function _a() {
        console.log("fired");
      }}
      value="ComboBox Entry 1"
    >
      <ComboBoxItem text="ComboBox Entry 1" />
      <ComboBoxItem text="ComboBox Entry 2" />
      <ComboBoxItem text="ComboBox Entry 3" />
      <ComboBoxItem text="ComboBox Entry 4" />
      <ComboBoxItem text="ComboBox Entry 5" />
    </ComboBox>
  );
```

### Reproduction steps

1. Open the code example above
2. Open the console
3. Open the dropdown
4. Verify the matching value is highlighted in the dropdown list
5. Click out of the dropdown (onBlur)
6. The console shows that the onChange Event was still fired, despite no real value change taking place
7. When repeating steps 3.-5. without refreshing the browser the onChange event will not get triggered

### Expected Behaviour

The onChange event should not be fired when no perceivable change is taking place

### Screenshots or Videos

After refresh:
![image](https://github.com/user-attachments/assets/4946b6c8-07b3-41bc-a479-b30390c05f10)

Open Dropdown. Matching Option is highlighted.
![image](https://github.com/user-attachments/assets/1f9810b2-d399-40aa-ac37-af7b5bd82c2e)

Click out of the dropdown. Console shows event has fired.
![image](https://github.com/user-attachments/assets/327f9ab4-7ebc-443a-b99c-6134e599e722)

### UI5 Web Components for React Version

1.29.8

### UI5 Web Components Version

1.24.8

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-08-26 08:09
Hi @lenafi5cher 

I couldn't reproduce the described behavior. Could you please check this [StackBlitz example](https://stackblitz.com/edit/github-hhal6y?file=src%2FApp.tsx,package.json) and video to see if I missed anything?

https://github.com/user-attachments/assets/bb1d6a56-6376-488e-8c67-f2a2ce40c85a

**Comment by lenafi5cher** [comment] 2024-08-26 10:41
Hi @Lukas742,
It doesn't seem like you missed anything. I tested your example both on- and offline, and did not see the bug I described either. I also retested my local example and still saw the issue. The only difference I perceive between your example and my bugged examples is that you are using `vite` and we use `webpack` or `react-scripts` which, looking at the dependencies of the latter, probably also relies on webpack. Maybe that has something to do with it?

**Comment by Lukas742** [comment] 2024-08-27 08:11
@lenafi5cher different bundling processes, transpilers, polyfills, etc., could indeed be causing the different behavior. In this case, I can't think of another reason either. However, I've personally never encountered issues with component specifics when switching between build tools or bundlers.

It might be related to the many deprecated dependencies when using CRA, which is why it's considered deprecated, even though it’s not explicitly marked as such, but even the [official React documentation](https://react.dev/learn/start-a-new-react-project#production-grade-react-frameworks) no longer mentions CRA.

To investigate further, I created a React app bootstrapped with CRA, but I couldn’t reproduce the issue there either. I’ve uploaded the code to GitHub with two branches - one using v1 and the other using v2. Could you please check them out and see if the behavior occurs for you? If so, could you provide the following details:

- Does this occur for both comboboxes? (`<ComboBox>` => cb using our wrapper, `<ui5-combobox>` => cb w/o our wrapper)
- OS and version?
- Browser and version?
- `@ui5/webcomponents-react` version?

Examples:
- Using **v1**: https://github.com/Lukas742/ui5wcr-cra/tree/issue/6254-combobox-v1
- Using **v2**: https://github.com/Lukas742/ui5wcr-cra/tree/issue/6254-combobox-v2

**Comment by lenafi5cher** [comment] 2024-09-02 07:21
Hi @Lukas742,
Testing v1 had the following results:
- I did not see any events fire either
- I copied over the package.json from the project where this issue occurs and tested again and the event still didn't fire. However, it still fires at my projects so I'm starting to think I am missing something in the implementation.

I found the culprit: the `index.tsx` file in your example imports `"@ui5/webcomponents-react/dist/Assets.js"`, our repository and my example do not. If I comment this import out in your example, I will see the events in the console.

So I suppose that is case closed...
Thanks for your help! :)

**Closed** 2024-09-02 09:38 UTC
Labels: bug, author action
