### ISSUE TITLE
[Switch]: [In High contrast black theme borders are getting overlapped with the ‘Switch button’.]

### ISSUE THREAD

**Issue by jadhavarjun** [SAP/ui5-webcomponents-react#6118] opened 2024-07-25 16:06 UTC
### Describe the bug

Here is my small piece of code and issues screenshot.
in all other themes working perfect but in **High Contrast Black Theme** getting border overlap issue.

**Code**
 <DialogFormField
                        name={`${currentConstraint}.isActive`}
                        as={SwitchField}
                        accessibleName={item.label}
                        switchId={item.constraintId}
                        onSwitchToggle={() => {
                          util.handleOnSwitchToggle({
                            switchHandlerId: item.constraintId,
                            active: item.isActive,
                            position: index,
                          });
                        }}
                        disabled={formType === FormType.VIEW ? true : false}
                        data-testid={item.constraintId + '-test-isActive'}
                        defaultValue={item.isActive}
                      />

Perfect working switch screenshot 
![image](https://github.com/user-attachments/assets/7c1ab968-6f3a-4616-8d6f-24716195938e)

Overlap issue screenshot
![image](https://github.com/user-attachments/assets/cbea73c9-fc61-4be5-b621-f2d9e3dd75db)

### Isolated Example

https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

In every theme UIs should not get truncated or overlapped with each other.

### UI5 Web Components for React Version

1.16.3

### UI5 Web Components Version

1.14.3

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment] 2024-07-26 07:26
Looks like this issue is caused by some styling in your application.
I've extraced it into a sandbox and there the styles are working fine: https://stackblitz.com/edit/js-xmcxkk?file=index.js,index.html,package.json

**Comment by Lukas742** [comment] 2024-08-05 07:13
Hi @jadhavarjun 

it turns out that this was a bug with the compact mode only. I've checked with the latest version and there it was fixed. 

- v1.24.8 of UI5 Web Components: https://stackblitz.com/edit/github-mr1mxi?file=package.json,main.js,index.html
- v1.14.3 of UI5 Web Components (broken): https://stackblitz.com/edit/github-mr1mxi-1sfat4?file=package.json,main.js,index.html

Please always try to add an isolated example of the issue, especially if it's with older versions.

Since this bug isn't reproducible in the latest build anymore, I'm going to close this issue.

**Closed by Lukas742** 2024-08-05 07:13 UTC
Labels: bug, author action
