### ISSUE TITLE
AnalyticalTable: column ordering is hard to use

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents-react#622] opened 2020-07-24 22:42 UTC
**Describe the bug**
Columns with a `Header` is hard to reorder. 50% of the time the text seems to be highlighted instead.

**Isolated Example**
https://codesandbox.io/s/cocky-easley-y0kj8?file=/src/App.js

**To Reproduce**
1) try to reorder the columns
=> text of column is usually highlighted, then trying to reorder again works (sometimes)
**Expected behavior**
I just think it's not clear where to click and drag on a column to reorder it.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.7
`@ui5/webcomponents-react` version: 0.9.11
Operating System:
Browser:

**Additional context**

**Comment by MarcusNotheis** [comment] 2020-07-29 06:50
Hey @stevetsanders,
in your codesandbox you are using a the tree table mode of the AnalyticalTable. We disabled column reordering on all columns when running a tree table mode because we had some issues with that combination.
When running in the "regular" mode, I wasn't able to reproduce the described behaviour.

Anyhow, there is an issue with column reordering in the `0.9.x` versions (the reordered column will be inserted in the wrong index), but this one is already fixed with #626.
We will release our `0.10.0` as soon as the UI5 Web Components have released their `1.0.0-rc.8`.

**Comment by stevetsanders** [comment] 2020-07-29 17:48
Hi @MarcusNotheis ,

are you saying issue #626 will fix the tree table reordering? Or will reordering not be supported in tree table mode?

**Comment by MarcusNotheis** [comment] 2020-07-30 14:21
Hey @stevetsanders,
not really. This PR is improving the experience of column reordering, but it still disabled in the TreeTable Mode. I'll look into enabling it for tree tables.

**Comment by MarcusNotheis** [comment] 2020-07-31 11:51
fixed by 3f91c84

**Comment by MarcusNotheis** [comment] 2020-07-31 14:34
Released in `0.10.1`.

**Closed by MarcusNotheis** 2020-07-31 14:34 UTC
Labels: bug
