### ISSUE TITLE
[DynamicPageHeader]: [Flicking when the viewport is scrolled past the header's bottom]

### ISSUE THREAD

**Issue by jpgmoreira** [SAP/ui5-webcomponents-react#5364] opened 2023-12-18 20:05 UTC
### Describe the bug

I am using a DynamicPage together with a DynamicPageHeader component.
I understand that the DynamicPageHeader component gets collapsed automatically when we scroll the page down so that the top of the viewport touches the header's bottom.
The problem is that when it happens, the DynamicPageHeader component gets removed from the page (as I saw on developer tools it gets a position absolute assigned), and it causes the content of the page below the header to move up a little bit, and as a result I get a "flicking" (moving upwards) of the content when the header collapses by scrolling.

In the code I added in the attached sandbox, I've just added some dummy text and a table to show this behavior. If you scroll down the page slowly, when the DynamicPageHeader element gets collapsed the table moves up a little because the header does not occupy any space on the page anymore. I've tested this with the code of the attached sandbox using a resolution of 1480 x 720.

Also notice that in the code (file App.jsx) I have a maxHeight style set to the DynamicPage. I need the content to not flick when the header collapses, even if this maxHeight is set like it is in the example.

### Isolated Example

https://codesandbox.io/p/sandbox/dynamicpageheader-flicking-wqnxwf?file=%2Fsrc%2FApp.jsx%3A106%2C25

### Reproduction steps

1. Run the application with the code in the attached sandbox, and a resolution of 1480 x 720;
2. Scroll the page slowly, until the dynamic header collapses automatically.
3. Observe that the table moved up a little when the header collapsed, because the header does not occupy any space anymore.

### Expected Behaviour

I expect that the content below the header does not move upwards when the header collapses by scrolling.

### UI5 Web Components for React Version

1.19.0

### UI5 Web Components Version

1.17.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2023-12-19 07:59
Hi @jpgmoreira 

your example isn't scrollable for me:
<img width="1537" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/9749730/5f7d30d8-8f0b-4db9-ac31-91b35f2b9efa">

From the description I would also say that this issue is a duplicate of #5269 which was fixed with [v1.23.0](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.23.0), so I'm closing this issue for now.

If these are not the same issues, please add a reproducible example using the latest version of `@ui5/webcomponents-react` to this issue, I will then reopen it.
If these are the same issues, but you have additional context or find that it wasn't fixed properly, then please explain that in the original issue.

**Closed by Lukas742** 2023-12-19 07:59 UTC
Labels: bug
