### ISSUE TITLE
[Object Page Component]: facets design inconsistencies

### ISSUE THREAD

**Issue by ShirSAP** [SAP/ui5-webcomponents-react#5811] opened 2024-05-16 11:21 UTC
### Bug Description

Today in the object page facet area, it seems that the display mode form are not using the correct parameters and padding.

This is how the component shows up without custom coding in our system:
![image](https://github.com/SAP/ui5-webcomponents/assets/109961433/21e25a1d-39ac-4785-b378-189b4305f5f3)
Both the form label as well as the paddings are incorrect.

### Affected Component

https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-objectpage--docs

### Expected Behaviour

Form Label should use:
![image](https://github.com/SAP/ui5-webcomponents/assets/109961433/83375b28-fee8-4bd5-994f-8cfaf625d911)
Form text value should use:
![image](https://github.com/SAP/ui5-webcomponents/assets/109961433/ff76fcb5-c6b5-4f4d-8eab-0da3ee50fcbd)

Taken from the following wiki: https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2697896853

In vertical layout the padding between label and text value should be:
![image](https://github.com/SAP/ui5-webcomponents/assets/109961433/7c86844f-2a3c-4fe1-869d-1164ff489cc8)

Taken from the following wiki: https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698913658

### Steps to Reproduce

1.
2.
3.
...

### Priority

Medium

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

OS

### Organization

SAP Build

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by ilhan007** [comment] 2024-05-16 11:28
Hello @ShirSAP and colleagues
 there is no Object Page in UI5 Web Components project, the links  from the issue description are from the UI5 Web Components For React Project => transferring the issue to https://github.com/SAP/ui5-webcomponents-react repository.

**Comment by Lukas742** [comment] 2024-05-16 12:28
Hi @ShirSAP 

although the screenshots you posted don't contain any sensitive information, please be aware that this is a public GitHub repository and that we generally delete content that we think might be compromising or just shouldn't be made public. I only mention this to raise awareness - it's always better to be safe than sorry.

> This is how the component shows up without custom coding in our system:

The `DynamicPageHeader` accepts any content developers define, so without a reproducible example I can't really tell what components you used. Please add an isolated, reproducible example by using this [StackBlitz template](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx), so we can assist you further.

Also, we're currently not offering any "Facet" components, so it's up to developers to define them on their end. If you feel like one of these facets should be available as component, please create a feature request for the respective component.

> In vertical layout the padding between label and text value should be:

Since you have linked the specifications of the `Form` component here, I have checked them and found no inconsistencies with our implementation. If I have missed something, please indicate specifically what is not implemented according to the guidelines. Please note that only the visual aspect has to comply with the guidelines, e.g. it doesn't matter if we use gap instead of padding, it just has to reflect the values defined in the wiki.

**Closed as completed** 2024-05-23 09:55 UTC
Labels: author action, SAP Build
