### ISSUE TITLE
[Page]: [Layout broken]

### ISSUE THREAD

**Issue by langered** [SAP/ui5-webcomponents-react#6517] opened 2024-10-18 09:28 UTC
### Describe the bug

The Page layout seems to be broken. The footer is on the top of the page, even above the header.

Even in the official documentation the Page example is broken: https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/layouts-floorplans-page--docs

### Isolated Example

https://stackblitz.com/edit/github-rsdvbx?file=src%2FApp.tsx

### Reproduction steps

1. Open stackblitz example or documentation
2. See the simple page object example
3. See that the layout is broken

### Expected Behaviour

I expect the layout to be correct. The footer of the page should be at the bottom, not at the very top.

### Screenshots or Videos

<img width="1127" alt="image" src="https://github.com/user-attachments/assets/ca9ce2a8-0d5d-4861-977f-eca40cca25f5">

### UI5 Web Components for React Version

2.3.1

### UI5 Web Components Version

2.3.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-10-18 10:19
Hi @langered 

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/9981).

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/9981

**Closed by Lukas742** 2024-10-18 10:19 UTC
Labels: bug
