### ISSUE TITLE
List: Long text truncates after one line and doesn't wrap

### ISSUE THREAD

**Issue by saurabhmehta02** [SAP/ui5-webcomponents-react#5782] opened 2024-05-06 08:58 UTC
### Is your feature request related to a problem?

We are using `<List>` & `<StandardListItem>` components with multiple selection mode.
In some scenarios the text for each StandardListItem can be very long.
It truncates with ellipsis but there is no way user can see the full text.

### Describe the solution you'd like

We are using `<List>` & `<StandardListItem>` components with multiple selection mode.
In some scenarios the text for each StandardListItem can be very long.
It truncates with ellipsis and for accessible user the screen reader tool announces the full text.
**But** there is no way normal user can see the full text. There is no tooltip available and the text doesn't wrap to multiple lines.

Our requirement from UX design is to wrap the text to multiple lines so normal users can see the full text.
Please support wrapping of the next to multiple lines so user can see full text.

### Additional Context

Standalone example - https://codesandbox.io/p/sandbox/friendly-rubin-pz79kr?file=%2Fsrc%2FApp.js%3A10%2C24 

### Organization

SAP labs

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-05-06 10:03
Hi @saurabhmehta02 

the `StandardListItem` offers a `tooltip` prop (see [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-list--docs#standardlistitem)).

For wrapping behavior, there exists already an issue that is covering this topic. If you have additional questions or comments please address them in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/7524).

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/7524

**Closed by Lukas742** 2024-05-06 10:03 UTC
Labels: feature-request
