### ISSUE TITLE
[Bug][SF][1.29.10][List][A11y][Expected Fixed Time: ASAP] In JAWS browse mode, group content announcement on the left navigation is not in a logical order when using the arrow keys

### ISSUE THREAD

**Issue by wilson-xu-sap** [SAP/ui5-webcomponents-react#6379] opened 2024-09-18 03:10 UTC
### Describe the bug

With JAWS browse mode enabled -> When the user navigates the left navigation using the arrow keys -> Observed that 'group end' is announced immediately after the 'group start' header, without announcing any list items within the group which is incorrect behavior.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/v1/?path=/story/data-display-list--group-header-list-item-story

### Reproduction steps

With JAWS browse mode enabled -> When the user navigates the left navigation using the arrow keys -> Observed that 'group end' is announced immediately after the 'group start' header, without announcing any list items within the group which is incorrect behavior.

### Expected Behaviour

Ensure that the group content follows a logical order when navigating with the arrow keys, it should be 'group start header' -> 'list item' -> 'group end header'

### Screenshots or Videos

<img width="1339" alt="image" src="https://github.com/user-attachments/assets/73d9bfaa-7503-4629-a72b-9529d9f54fb1">

### UI5 Web Components for React Version

1.29.10

### UI5 Web Components Version

1.24.4

### Browser

Edge

### Additional Context

This is the reopen ticket for https://github.com/SAP/ui5-webcomponents/issues/9871. I cannot reopen that one.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-09-18 06:53
I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/9871).

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/9871

**Closed by Lukas742** 2024-09-18 06:53 UTC
Labels: bug

**Comment by wilson-xu-sap** [comment] 2024-09-18 06:58
Hope that person will reply that.
