### ISSUE TITLE
FileUploader: no way to reset file list

### ISSUE THREAD

**Issue by pmarkiewicz** [SAP/ui5-webcomponents-react#6586] opened 2024-11-04 11:09 UTC
### Describe the bug

I need to reopen same file few times, example scenario: upload, need to fix something, upload again. Current implementation blocks onChange to be raised after selecting same file.

### Reproduction steps

Use FileUploader and try to open same file twice

### Expected Behaviour

Either trigger event every time or have function to cleanup current file list

### UI5 Web Components for React Version

1.24.5

### UI5 Web Components Version

1.24.5

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-11-04 11:17
Hi @pmarkiewicz 

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents-react/issues/6381).

Duplicate of https://github.com/SAP/ui5-webcomponents-react/issues/6381

Also relevant: https://github.com/SAP/ui5-webcomponents/issues/9947

**Closed by Lukas742** 2024-11-04 11:17 UTC
Labels: bug
