### ISSUE TITLE
AnalyticalTable: onRowSelect and onRowClick both event triggered on selection

### ISSUE THREAD

**Issue by kmanisha29** [SAP/ui5-webcomponents-react#5524] opened 2024-02-23 12:13 UTC
### Describe the bug

Analytical table with multiselect somehow triggers both click and select handler on row selection.
Even with RowSelector as SelectionBehavior where clicking on row does not select the row, If we select row from checkbox, still onRowClick handler triggered along with onRowSelect handler.

Need both handler for different features- select for selection and click for additional purpose eg: navigation

### Isolated Example

https://stackblitz.com/edit/github-3wiuce?file=src%2FApp.tsx

### Reproduction steps

1. Create a table using Analytical table and provide data, columns , selectionMode as MultiSelect .
2. Provide handlers for onRowSelect and onRowClick
3. Click on row, OnRowClick handler will be triggered.  [ Row won't be selected with selectionBehavior as RowSelector else onRowSelect also called] 
4. Select a row using checkbox on row. Both onRowClick and onRowSelect handlers triggered.
...
****

### Expected Behaviour

clicking on checkbox to select the row should only trigger onRowSelect.
onRowClick should not be fired in case of RowSelector with checkbox selection.

### UI5 Web Components for React Version

1.19.0

### UI5 Web Components Version

1.17.2

### Browser

Edge

### Operating System

Windows

### Additional Context

onRowSelectionChange is provided by react-table which can be used for only selection change. Though this is not exposed in UI5 react web component

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-02-23 16:12
Hi @kmanisha29 

this behavior is by design, as the row was still clicked, so in my opinion it would be wrong not to fire the event in this case.

You can check in the `target` of the `onRowClick` event for the `selectionCell` dataset entry. If it equals `"true"` then the selection cell was clicked. We also outline this in our [documentation](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable-recipes--docs#how-to-distinguish-between-onrowclick-and-onrowselect-on-selection-cell-click), but I noticed that we've made a fundamental error in the example (treating a `string` like a `boolean` :facepalm:) so you can ignore it until the linked PR is merged and released.

I've also updated your [stackblitz](https://stackblitz.com/edit/github-3wiuce-r6ptq8?file=src%2FApp.tsx) example to show this behavior.

**Closed** 2024-02-26 07:25 UTC
Labels: documentation
