### ISSUE TITLE
[SF][Menu]: Menu cannot be opened in responsive mobile mode

### ISSUE THREAD

**Issue by summer2200** [SAP/ui5-webcomponents-react#5563] opened 2024-03-01 16:06 UTC
### Describe the bug

Menu cannot be opened in browser's responsive mobile mode, error throws when click button to open it.
<img width="1508" alt="Screenshot 2024-03-01 at 23 59 05" src="https://github.com/SAP/ui5-webcomponents-react/assets/18187036/9c946f42-1ed5-4afe-aae3-ee35e7679635">

It can work normally in web mode:
<img width="1510" alt="Screenshot 2024-03-01 at 23 59 55" src="https://github.com/SAP/ui5-webcomponents-react/assets/18187036/366c2786-c68b-48b1-b68f-0cb628026b54">

### Isolated Example

https://codesandbox.io/p/sandbox/menu-pd535x?file=%2Fsrc%2FApp.js%3A10%2C18

### Reproduction steps

1. Open codesandbox
2. Open the demo in a new browser tab
3. Open dev tool and switch to mobile mode
4. Click button to open the menu
...

### Expected Behaviour

Menu should be opened in browser's mobile mode

### UI5 Web Components for React Version

1.25.1

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Operating System

macOS Sonoma 14.3.1

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-03-01 16:44
Hi @summer2200 

I will close this issue as there is already [another one](https://github.com/SAP/ui5-webcomponents/issues/7767) covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/7767

**Closed by Lukas742** 2024-03-01 16:44 UTC
Labels: bug
