### ISSUE TITLE
[SF][DynamicPageTitle]: The space is too big when the overflow button is shown

### ISSUE THREAD

**Issue by ericchan1983** [SAP/ui5-webcomponents-react#2042] opened 2021-08-27 09:45 UTC
**Describe the bug**
When there are two buttons on the page title, and open the page in a small screen then the overflow button is shown.
The space between the first button and the overflow button is too big.

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**

**Expected behavior**
The space should be as the following:
![image](https://user-images.githubusercontent.com/1614528/131108298-c6dcaf2a-0047-45e9-afc1-ab1fbb4b2c33.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1614528/131107655-505ad3f4-4ff6-4b7e-86f6-95aacc323581.png)
**UI5 Web Components for React Information**
`@ui5/webcomponents` version:0.31.14
`@ui5/webcomponents-react` version:0.131.13
Operating System:macOS Big Sur
Browser: Chrome Version 92.0.4515.159 (Official Build) (x86_64)

**Additional context**

**Comment by Lukas742** [comment] 2021-08-30 11:35
Hi @ericchan1983 

since this is a duplicate of https://github.com/SAP/ui5-webcomponents-react/issues/2032, I'm closing this issue.

**Closed by Lukas742** 2021-08-30 11:35 UTC
Labels: bug, SF
