### ISSUE TITLE
AnalyticalTable: Select|DatePicker components in Cell do not work as expected

### ISSUE THREAD

**Issue by gnseo** [SAP/ui5-webcomponents-react#343] opened 2020-03-11 05:02 UTC
**Describe the bug**
When we use Select or DatePicker component in Cell, the Options for Select and Calendar for DatePicker was not displayed as expected.

**To Reproduce**
Go to following link, you can reproduce the issue.
https://codesandbox.io/s/select-datepicker-on-table-ttiy9

**Screenshots**
When I click the Calendar opener, the error messages are shown like below screenshot.
![Screen Shot 2020-02-27 at 1 34 34 PM](https://user-images.githubusercontent.com/12092761/76383856-82e22f80-63a0-11ea-8e70-5de14adef00e.png)

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version: 0.8.4

**Comment by MarcusNotheis** [comment] 2020-03-12 13:53
Hi @gnseo 
thanks for submitting this issue. It looks like that the root cause of this error is already fixed in the underlying UI5 Web Components library. As soon as they release a new version we'll update as well. I'll keep this issue open until we have updated.

**Comment by gnseo** [comment] 2020-03-13 04:11
Thank you for the feedback.
Hope they release the new version soon.

**Comment by MarcusNotheis** [comment] 2020-04-03 07:19
Released in `@ui5/webcomponents-react@0.9.0-rc.9`

**Closed by MarcusNotheis** 2020-04-03 07:19 UTC
Labels: bug, ui5-webcomponents
