### ISSUE TITLE
[Page]: Floating footer horizontal spacing is broken

### ISSUE THREAD

**Issue by skowrons** [SAP/ui5-webcomponents-react#6418] opened 2024-09-29 09:45 UTC
### Describe the bug

When adding a floating footer to a page the border will be displayed two times and the horizontal padding will not be applied correctly.

### Isolated Example

https://stackblitz.com/edit/github-fvfcqj?file=src%2FApp.tsx

### Reproduction steps

1. Add `Page` component
2. Add `Bar` in `footer` slot

### Screenshots or Videos

Example in storybook (screenshot):

![Bildschirmfoto 2024-09-29 um 11 38 19](https://github.com/user-attachments/assets/d9af2bc2-b0e6-4d09-9427-8af9b96836f9)

### UI5 Web Components for React Version

2.1.1

### UI5 Web Components Version

2.2.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-09-30 06:53
Hi @skowrons 

I will close this issue as there is already [another one](https://github.com/SAP/ui5-webcomponents/issues/9756) covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/9756

**Closed by Lukas742** 2024-09-30 06:53 UTC
Labels: bug
