### ISSUE TITLE
[Toolbar(V2) Subcomponents]: Additional according to Fiori

### ISSUE THREAD

**Issue by gitgdako** [SAP/ui5-webcomponents-react#6466] opened 2024-10-08 11:27 UTC
### Is your feature request related to a problem?

Toolbar (V2 in 1.x)
https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/layouts-floorplans-toolbar--docs
has a very limited amount of subcomponents.
According to 
https://experience.sap.com/fiori-design-web/toolbar-overview/
other elements are not prohibited and using 1.x we displayed Switches, Labels, Segmented Buttons etc.
Due to the limited number of subcomponents we can not upgrade to ToolbarV2 or webcomponents 2.x without having to fall back to the compat Toolbar

### Describe the solution you'd like

ToolbarV2 allows most common input elements, ideally those listed in
https://experience.sap.com/fiori-design-web/toolbar-overview/#overflow-generic

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-10-09 07:45
Hi @gitgdako 

I will close this issue as there is already [another one](https://github.com/SAP/ui5-webcomponents/issues/9851) covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/9851

**Closed by Lukas742** 2024-10-09 07:45 UTC
Labels: feature-request
