### ISSUE TITLE
[SF][Text]: [Long string is not wrapped in flex container]

### ISSUE THREAD

**Issue by Jasonl157** [SAP/ui5-webcomponents-react#5949] opened 2024-06-20 18:26 UTC
### Describe the bug

With the default wrapping, when the `Text` is a long string and inside a flex container, it's not wrapped

### Isolated Example

https://stackblitz.com/edit/github-1yycgh-wodi7h?file=src%2FApp.tsx

### Reproduction steps

1. Open the StackBlitz link shared.
2. You can see that the first `Text` overflows. In contrast to that, the second `Text` with `overflow-wrap: anywhere` is wrapped

### Expected Behaviour

Long string inside flex container is wrapped

### Screenshots or Videos

<img width="512" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/131832797/c09c6632-259e-46b2-be50-ffe280c80f76">

### UI5 Web Components for React Version

1.29.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-06-21 06:29
Hi @Jasonl157 

the `Text` uses `overflow-wrap: break-word` and since your text is is just a single long word, it doesn't wrap. 
If you want to wrap text anywhere, then the setting the CSS property to `anywhere` as you did is the correct approach.

Since this behavior is by design, as words are typically not that long, I'm closing this issue.

**Closed by Lukas742** 2024-06-21 06:29 UTC
Labels: consulting
