### ISSUE TITLE
[SAP][VERY-HIGH]onClick event is getting fired even if button is disabled

### ISSUE THREAD

**Issue by thisisjasmeet** [SAP/ui5-webcomponents-react#4062] opened 2023-01-31 04:54 UTC
**Describe the bug**

**Isolated Example**
https://codesandbox.io/s/sad-david-mr70j3?file=/src/App.js

**To Reproduce**
1. Add onClick to button or split button 
2. disable button.split button 

**Expected behavior**
OnClick should not get called

**UI5 Web Components for React Information**
"@ui5/webcomponents": "1.10.4-rc.0",
    "@ui5/webcomponents-fiori": "1.10.4-rc.0",
    "@ui5/webcomponents-react": "~1.8.0",
    
Operating System: mac
Browser: chrome

**Additional context**
This is for internal SAP and this issue is breaking our code so please fix this on prio

**Comment by MarcusNotheis** [comment] 2023-01-31 06:48
Hi @thisisjasmeet,

thanks for reporting. The issue is already known and tracked in the UI5 Web Components Repo via https://github.com/SAP/ui5-webcomponents/issues/6372. Please follow this issue for updates.

Closing this issue as duplicate.

**Closed by MarcusNotheis** 2023-01-31 06:48 UTC
Labels: bug
