### ISSUE TITLE
AnalyticalTable: Shows horizontal scrollbar when it shouldn't

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#3376] opened 2022-08-16 18:00 UTC
**Describe the bug**
We have a SplitterLayout with a vertical splitter and two SplitterElements. The right-hand SplitterElement contains an empty div, the left-hand SplitterElement contains an AnalyticalTable. The table has `inlineSize: '100%'` set on it so it fills the entire SplitterElement (horizontally). This lets us resize the table. If we move the splitter, we will see that as the AnalyticalTable resizes, it will sometimes display a horizontal scrollbar, sometimes it won't.

I have not been able to figure out a pattern. At first, I suspected it has something to do with the fact that if the table has a floating point width like e.g. 802.8px, each row object will have the width rounded up, in this case 803px. But this doesn't seem to be the problem, I for example see a scrollbar for 802.8px/803px, but not for 799.8px/800px.

I've attached screenshots showing the width of the table header (floating point width) vs the table header row (rounded width), in case it has something to do with that.

**Isolated Example**
If it worked, here's a [sandbox](https://codesandbox.io/s/wonderful-framework-yt9bqu?file=/src/App.js).
If it didn't, here's the code (App.js of the suggested sandbox):
```
import React from "react";
import {
  SplitterElement,
  SplitterLayout,
  AnalyticalTable,
  ThemeProvider,
  ShellBar
} from "@ui5/webcomponents-react";

export default function App() {
  const table = (
    <AnalyticalTable
      data={[
        {
          name: "Germany",
          path: ["Germany"],
          country: undefined,
          description: undefined
        },
        {
          name: "France",
          path: ["France"],
          country: undefined,
          description: undefined
        }
      ]}
      columns={[
        { id: "name", accessor: "name", Header: "ID" },
        { id: "description", accessor: "description", Header: "Description" }
      ]}
      subRowsKey={"children"}
      style={{
        inlineSize: "100%",
        blockSize: "100%"
      }}
    />
  );

  return (
    <ThemeProvider>
      <ShellBar primaryTitle="UI5 Web Components for React Issue Template" />
      <SplitterLayout
        style={{
          inlineSize: "100%",
          blockSize: "100%"
        }}
      >
        <SplitterElement size="70%">{table}</SplitterElement>
        <SplitterElement size="30%">
          <div style={{ width: "100%" }} />
        </SplitterElement>
      </SplitterLayout>
    </ThemeProvider>
  );
}
```

**To Reproduce**
Just move the slider. Heads up though, I wasn't able to ever get rid of the scrollbar in the sandbox. In storybook, it will randomly appear or disappear as I move the slider, let go, and the table resizes.

**Expected behavior**
The expected behavior is to not have a horizontal scrollbar as the table fits neatly into its surrounding container.

**Screenshots**
![tableheaderrow](https://user-images.githubusercontent.com/110408767/184950817-2e5c96b9-3294-4e03-a422-bac71076a78b.png)
![tableheader](https://user-images.githubusercontent.com/110408767/184950823-94fc1abb-4a79-4426-bee2-07ca83718413.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "1.4.0"
`@ui5/webcomponents-react` version: "0.23.2"
Operating System: Win10
Browser: Chrome

Thanks a lot in advance!

**Comment by Lukas742** [comment] 2022-09-27 13:48
Hi @ej612 

your codeSandbox is using 0.27.x of `@ui5/webcomponents-react`, which does not include the fix. I tried reproducing with the latest version but wasn't able to (see video). Could you please check if the version was causing this issue? If an unnecessary scrollbar is still rendered even with the newest version for you, could you please let us know your screen resolution of the codeSandbox window when the error occurs (preferably without iframe - for this you can click on the button on the top right of the codesandbox browser window), your OS and browser you are using?

https://user-images.githubusercontent.com/9749730/192543770-c45a34dc-8d0b-4cd8-b61e-04dc7d951367.mp4

**Comment by Lukas742** [comment] 2023-09-28 07:06
Fixed by #4899

**Comment by Lukas742** [comment] 2023-10-23 06:46
Hi @ej612 

I could not reproduce the issue. At what resolution does this occur and what browser and OS are you using?

https://github.com/SAP/ui5-webcomponents-react/assets/9749730/08f77bb7-1f6d-40b6-b9fa-0b4991e1a024

**Comment by Lukas742** [comment] 2023-11-15 14:18
Hi @ej612 

this sounds like a [subpixel](https://en.wikipedia.org/wiki/Subpixel_rendering#:~:text=Subpixel%20rendering%20requires%20the%20software,4%20colors%20like%20RGBW%20squares.) problem to me. Unfortunately I don't think that there is a way to fix this as it can differ from browser to browser and monitor to monitor. In short it all comes down to rounding issues of our column size calculation, but even with our workaround (using `getBoundingClientRect` instead of `offsetWidth`) we can't prevent this in all cases.

**Closed by Lukas742** 2023-11-15 14:18 UTC
Labels: bug, released

**Comment by Lukas742** [comment] 2023-12-15 09:12
Hi @ej612 

> I spent some more time looking into this issue and was able to narrow it down: The problem occurs when the width of the AnalyticalTable is not a whole number. In this case, the table will round its scrollWidth to the nearest integer, making the scrollbar appear: [...]
> This may or may not be related to the fact that the rows of the table also seem to have their width rounded up, as I described in my opening post.

I may have found a [fix](https://github.com/SAP/ui5-webcomponents-react/pull/5352) and created a snapshot release (`0.0.0-05297a79b2`) that includes it. Could you please test if this solves the issue on your end as well? Please note, that when the page is scaled (`scaleXFactor` is set and `transform: scale(x)` is applied), there most probably still will be an unnecessary scrollbar visible in some cases.

> Update: The AnalyticalTable seems to be generally allergic to dimensions that are not whole numbers. I managed to trap it in an infinite loop when given the right dimensions. I made a [sandbox](https://codesandbox.io/s/thirsty-keldysh-xptf6d?file=/src/App.js).

This looks like a different bug to me. Unfortunately I was again not able to reproduce it...
Could you create another issue for this bug and also include the sandbox, the browser you're using, the resolution of your monitor and OS.

**Comment by Lukas742** [comment] 2023-12-15 11:26
Perfect! We'll publish the fix with our next release then. :)
