### ISSUE TITLE
[CustomElementsScope]: [setCustomElementsScopingSuffix will cause style broken, shadowDOM missing]

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#6549] opened 2024-10-24 07:51 UTC
### Describe the bug

[CustomElementsScope]: [setCustomElementsScopingSuffix will cause style broken, shadowDOM missing]
Use setCustomElementsScopingSuffix and setCustomElementsScopingRules to customize ui5 tags in my project, and then all style broken

### Isolated Example

https://stackblitz.com/edit/github-wmf1wn-r8quu1?file=src%2Fmain.tsx

### Reproduction steps

1. Enter in example
2. See that whole style broken
3. Comment out codes of setCustomElementsScopingSuffix in main.tsx, from line 12 to line 16, style resumed
4. So the conclusion is that in this version of UI5, the setCustomElementsScopingSuffix will cause style broken
...

### Expected Behaviour

Style shold works, shadow dom attached

### UI5 Web Components for React Version

~2.3.0

### UI5 Web Components Version

~2.3.0

### Browser

Chrome

### Operating System

MAC OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-10-24 09:02
Hi @JackieWei 

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/10016).

The solution for this problem is also described in the original issue. In essence `setCustomElementsScopingSuffix` needs to be called before any custom element was defined (component imported). I adjusted your example to show how this could be achieved: https://stackblitz.com/edit/github-wmf1wn-xu3vcw?file=src%2FapplyScoping.ts,src%2Fmain.tsx

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/10016

**Closed by Lukas742** 2024-10-24 09:02 UTC
Labels: bug
