### ISSUE TITLE
Tree/TreeItemCustom: Cant input SPACE nor use ARROW KEYS correctly within Input fields.

### ISSUE THREAD

**Issue by bsremcevic** [SAP/ui5-webcomponents-react#5635] opened 2024-03-22 15:25 UTC
### Describe the bug

When using Tree component with TreeItemCustom as children, and adding Input field to each TreeItemCustom as a content.
Input fields will not enter SPACE character nor will use arrow keys to navigate through the text inside the Input field.
SPACE reserved key 'normal' behavior to select the row should be disabled by setting 'mode' to 'none' on Tree component, as stated in the documentation.

Current behavior:
SPACE cant be entered (unless used with SHIFT - not noted anywhere in the documentation) - highlights the row.
ARROW KEYS - collapses or expands child TreeItems.

### Isolated Example

https://codesandbox.io/p/sandbox/bug-on-edit-input-for-analytic-table-forked-3khft3?file=%2Fsrc%2FApp.js

### Reproduction steps

1. Use Tree component, with TreeItemCustom as children in order to put custom content inside the tree items.
2. Then add Input field inside the content.
3. Set Tree component 'mode' to 'none'.
4. Set onKeyDown handlers to stopPropagation.
5. Once inside the Input field try entering SPACE or using ARROW KEYS if focused on some child TreeItem.

### Expected Behaviour

SPACE should be entered in the Input field as any other character.
Arrow Keys should move through the text in the Input field.

### UI5 Web Components for React Version

1.24.0

### UI5 Web Components Version

1.21.2

### Browser

Chrome, Edge, Firefox

### Additional Context

Some of the offered solutions on other issues on GitHub were mentioning to add event.stopPropagation() to the callback.
But in this case this is not resolving the issue. For both SPACE and ARROW keys.
Tried with both onKeyDown and onKeyUp (due to documentation that mentions keyup).

Side note:
Same behavior is with analytical table if 'isTreeTable' is set.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-03-26 14:32
Hi @bsremcevic 

we moved to [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) as our preferred web IDE/sandbox as it's not possible anymore to edit codeSandboxes with a free plan.

___

The reason why `event.stopPropagation()` isn't working as intended is the way how React handles "native" events. Our wrapper binds all custom events of the web component via `addEventListener` to the respective component, but this is not the case for native events like `keydown`.

The current behavior with `onKeyDown` on the `Input` is:

- `keydown` of the Input is registered on the React root and handled internally by the SyntheticBaseEvent of React.
- `keydown` of the `li` inside the shadow root of the web component that is responsible for preventing the default behavior, is registered on the element itself and the standard JS Event delegation is applied. Also, as far as I know, these events are always calling their handler in the bubbling phase (default for `addEventListener`).

Because of this the handler of the `keydown` event of the `Input` is called after the `keydown` of the `li` which makes stopping event propagation not possible.

To prevent bubbling, you have to make sure that the handler is executed before the handler of the internal `keydown` event. You can achieve that by registering the event via `addEventListener` yourself, also you could use `onKeyDownCapture` React event, but I'm not sure if this has other side effects.

[Here](https://stackblitz.com/edit/github-cmrham?file=src%2FApp.tsx) you can find an example implementing both options.

Since there's already an [issue](https://github.com/SAP/ui5-webcomponents/issues/7566) in the ui5-webcomponents repo, I'm going to close this one. If you have any questions regarding the `Tree` implementation or more information, please address them in the original issue. 
If you have more information or any questions regarding our wrapper implementation, feel free to add them here, as we also monitor closed issues.

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/7566

**Closed by Lukas742** 2024-03-26 14:32 UTC
Labels: bug

**Comment by bsremcevic** [comment] 2024-04-01 09:50
Thank you very much @Lukas742,

this indeed helped and addressed the issue I had.

I tried both approaches and both solve the problem.
Although the suggested solution had some side effects when hard refreshing, which was probably due to local implementation, onKeyDownCapture did not have any side effects.

Once more, thank you.
