### ISSUE TITLE
input: The should not be multiple tab stops for a Single ui component

### ISSUE THREAD

**Issue by pppwr7** [SAP/ui5-webcomponents-react#5976] opened 2024-06-26 04:00 UTC
### Describe the bug

For Input field with interactive icon added, if the current focus is on the input field then on tab key press the focus moves to the interactive icon. As per the UX guideline, for any UI only 1 tab stop should be provided. This issue has been raised by the UX colleague.

### Isolated Example

https://stackblitz.com/edit/github-zbkxaj?file=src%2FApp.tsx

### Reproduction steps

1. open https://stackblitz.com/edit/github-zbkxaj?file=src%2FApp.tsx
2. keep the focus on input field
3. hit tab key and see that the icon as well as the input box is focused. Ideally, the control should move to next component away from the input field

### Expected Behaviour

should be focussed aut of the input field on tab press

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-06-26 06:35
Hi @pppwr7 

this seems like the same issue that you opened about one month ago, so I'm closing this as duplicate.

Also, if you want to render a clear button inside of it, why don't you use the `showClearButton` prop? This way there's no focus on the button and the button is styled according to specs.

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/8970

**Closed by Lukas742** 2024-06-26 06:35 UTC
Labels: bug

**Comment by pppwr7** [comment] 2024-06-26 06:53
Hi [Lukas742](https://github.com/Lukas742)
We have usecase to show search as the icon and on click of it ,we have to fire a call to get the data. I have create 2 issues, one for the tab press and another for the double focus.

**Comment by Lukas742** [comment] 2024-06-26 07:12
If the focus is received via tabbing or by clicking is basically the same behavior, so in my opinion this is the same issue. If you feel like this should be handled separately, I can still transfer this issue to the ui5-webcomponents repo, so our colleagues there can decide how to handle it.

**Comment by pppwr7** [comment] 2024-06-26 07:58
Hi [Lukas742](https://github.com/Lukas742) 
Please transfer it to the ui5-webcomponents repo. I see that there is a different component for this usecase called SearchField refer https://ui5.sap.com//#/entity/sap.m.SearchField/sample/sap.m.sample.SearchField. The behavior is also as we expect in our usecase - no double focus, no tabbing into the search icon. We need the similar behavior in input control provided for the react side.
