### ISSUE TITLE
[Input]:[Chrome password autofill causes error "Cannot read properties of undefined (reading 'inputType')"]

### ISSUE THREAD

**Issue by gregor-vag** [SAP/ui5-webcomponents-react#5800] opened 2024-05-14 09:56 UTC
### Describe the bug

When starting the application, an input field used for "username" and another for "password".
Chrome fills in the password automatically which causes the following error.
The field is filled in UI component, but seems not to be filled internally.

### Reproduction steps

1. 
2.
3.
...

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/157693975/75692a45-964e-42c1-9216-afda178f1a00)

![image](https://github.com/SAP/ui5-webcomponents-react/assets/157693975/4bb4e166-7834-457a-b712-a70947648925)

![image](https://github.com/SAP/ui5-webcomponents-react/assets/157693975/9fefb81f-e0cb-4809-8aaa-706b22d0141d)

### UI5 Web Components for React Version

1.28.1

### UI5 Web Components Version

1.24.3

### Browser

Chrome

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-05-14 10:53
Hi @gregor-vag 

I will close this issue as there is already [another one](https://github.com/SAP/ui5-webcomponents/issues/8706) covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/8706

**Closed by Lukas742** 2024-05-14 10:53 UTC
Labels: bug

**Comment by jackydev1** [comment] 2024-10-03 01:44
Hi I am encountering the exact issue mention here. I see that the link above is pointing to ui5-webcomponents. Is this fixed for i5-webcomponents-**react** Input as well?
