### ISSUE TITLE
[Table]: Table headers are not displayed for Table component imported from webcomponents-react-compat

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents-react#6705] opened 2024-12-06 17:03 UTC
### Describe the bug

Table headers are not displayed for Table component imported from webcomponents-react-compat
It is clearly reproduced in webcomponents docs https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/legacy-components-table--docs&args=overflowMode:Popin

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/legacy-components-table--docs&args=overflowMode:Popin

### Reproduction steps

1.https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/legacy-components-table--docs&args=overflowMode:Popin

### Expected Behaviour

Table headers should be rendered

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/54798d4b-2b23-4a48-a46b-7c1cff631192)

### UI5 Web Components for React Version

2.4.0

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-12-09 07:16
Hi @lateefsofi 

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents-react/issues/6553).

Duplicate of https://github.com/SAP/ui5-webcomponents-react/issues/6553

**Closed by Lukas742** 2024-12-09 07:16 UTC
Labels: bug
