### ISSUE TITLE
FlexibleColumnLayoutComponentName: Scrolling not working properly in Start Column when other columns are open

### ISSUE THREAD

**Issue by knandan15** [SAP/ui5-webcomponents-react#3664] opened 2022-10-20 11:11 UTC
**Describe the bug**
Scrolling not happening properly with mouse scroll button or keyboard arrow keys in the Start Column when other columns are open.

**Isolated Example**
https://codesandbox.io/s/dynamicpage-flexiblecolumn-forked-zwcbpm

**To Reproduce**
1. Go to https://codesandbox.io/s/dynamicpage-flexiblecolumn-forked-zwcbpm
2. Open the web page in New Window 
3. Click on any entry in the row so that Flexible Layout opens from the right.
4. One the midColumn is opened, try scrolling the startColumn. It is not getting scrolled down and abruptly coming back up.

**Expected behavior**
Normal scrolling should happen in the startColumn.

**Screenshots**
![FCL Scroll Bug](https://user-images.githubusercontent.com/48648230/196933266-bbf150d2-8698-425d-bb36-ecf48e074a1e.PNG)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "^1.6.0"
`@ui5/webcomponents-react` version: "0.28.2"

**Comment by Lukas742** [comment] 2022-10-20 11:16
I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate of #3623

**Closed by Lukas742** 2022-10-20 11:16 UTC
Labels: bug
