### ISSUE TITLE
Popover: Allow HTMLElement as opener

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#4096] opened 2023-02-06 12:26 UTC
The `opener` prop of the [`Popover` component](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-popover--default-story#properties) only accepts a string ID of the respective element.
In our use case, we have a list of an unknown number of elements and want to display a popover on each element. This would require us to generate unique IDs for each element, which isn't trivial to do in React < 18 where the useId hook doesn't exist yet. I've seen workarounds where an `<IdContextProvider>` is wrapped around the application that keeps track of how many unique Ids it has generated and increases the counter by 1 everytime a new one is requested. Before resorting to a such contraption, however, I wanted to ask if it was possible to make `opener` accept an HTMLElement, the way the opener prop of the [Menu component ](https://sap.github.io/ui5-webcomponents-react/iframe.html?viewMode=docs&id=modals-popovers-menu--default-story&args=#properties) does.

Thanks a lot in advance!

**Comment by Lukas742** [comment] 2023-02-06 13:18
Hi @ej612 

the `Menu` doesn't accept an HTMLElement as opener as well, this was something we overlooked when running our script. This [PR](https://github.com/SAP/ui5-webcomponents-react/pull/4097) will fix that.

I also added an explanation on how you can pass a reference of an element to the `opener` property of the web component in this PR. This is the explanation for the Popover as it will be available with our next release in our documentation.

> **Opening a `Popover` by reference and not by `id`**
> 
> The web component exposes a way to pass a reference of an element instead of an `id` to the `opener` prop. Since this is not supported when passing the reference in a declarative way to a React `prop`, you have to attach the ref directly on the web component.
> You can do that by e.g. leveraging a React Ref, and then set the corresponding property there.
> 
> <MessageStrip hideCloseButton>
>   Changing properties outside of the React rendering cycle can lead to unwanted behavior, please be extra cautious when
>   using this approach!
> </MessageStrip>
> 
> ```jsx
> const PopoverComponent = () => {
>   const popoverRef = useRef(null);
>   const [open, setOpen] = useState(false);
>   const handleOpenerClick = (e) => {
>     if (popoverRef.current) {
>       popoverRef.current.opener = e.target;
>       setOpen((prev) => !prev);
>     }
>   };
>   return (
>     <>
>       <Button onClick={handleOpenerClick}>Opener</Button>
>       <Popover ref={popoverRef} open={open}>
>         {/* Content */}
>       </Popover>
>     </>
>   );
> };
> ```

**Comment by MarcusNotheis** [comment] 2023-03-31 11:56
Hi @ej612,

I think the solution here is to omit implementing the `onKeyDown` behaviour because the button has a built-in logic which fires the `onClick` when the enter or space key is pressed.

I just tried to comment out the `onKeyDown` logic in your sandbox and the opening/closing the menu both via click and keydown was working fine for me.

Does that work for you?

**Comment by MarcusNotheis** [comment] 2023-03-31 14:53
Hi @ej612 

I tried to reproduce the issue in a very simple AnalyticalTable and in the codesandbox it works fine: https://codesandbox.io/s/xenodochial-curran-ld81zy

As discussed via chat I'm going to close this issue.

**Closed by MarcusNotheis** 2023-03-31 14:53 UTC
Labels: author action
