### ISSUE TITLE
[VariantManagement]: [Application in width equivalent to 320 CSS pixels, ‘Save as’, ‘Manage’ buttons associated within ‘Standard’ dialog are getting truncated]

### ISSUE THREAD

**Issue by sanjayC5373903** [SAP/ui5-webcomponents-react#5895] opened 2024-06-06 12:02 UTC
### Describe the bug

<VariantManagement
      ref={vmFieldRef}
      onSelect={e => updateVariantId(e.detail.selectedItems[0].id)}
      onSaveManageViews={e => handleOnSaveManageViews(e, onSaveManageView,setIsStandardAutoApplyMsgBox)}
      closeOnItemSelect={true}
      dirtyState={isVariantDirty}
      onSaveAs={e =>
        handleVariantOnSave({
          event: e,
          currentVariant: currentVariant,
          handleVariantSave: handleVariantCreate,
          setNewVariantDetails: setNewVariantDetails
        })
      }
      onSave={e =>
        handleVariantOnSave({
          event: e,
          currentVariant: currentVariant,
          handleVariantSave: handleVariantEdit,
          setNewVariantDetails: setNewVariantDetails
        })
      }
      data-testid="VariantManagementField"
      onFocus={e => handleAria(e)}
    >
      {variantList?.map(item => {
        return (
          <VariantItem
            aria-label={item.viewName}
           // placement="right"
            selected={parseInt(item.id) === parseInt(currentVariant.id)}
            id={item.id}
            global={item.public}
            data-testid="VariantItemField"
            author={item.createdBy}
            isDefault={item.default}
            applyAutomatically={item.autoApply}
            hideDelete={item.userId !== currentUserId}
            labelReadOnly={item.userId !== currentUserId}
            readOnly={item.userId !== currentUserId}
            key={item.id}
          >
            {item.viewName}
          </VariantItem>
        );
      })}
    </VariantManagement>
    
    Here we using default placement bottom. popover open at bottom side. but the popover size is not looking proper. and variant item also not display. we loss the content. see below image.
    
    
<img width="815" alt="Screenshot 2024-06-06 165549" src="https://github.com/SAP/ui5-webcomponents-react/assets/170628934/43669aeb-db02-45c7-9fa2-77f94ddeee15">

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

The contents should be present at a width equivalent to 320 CSS pixels without loss of information or functionality

### UI5 Web Components for React Version

0.27.5

### UI5 Web Components Version

1.6.0

### Browser

Chrome

### Operating System

Windows11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by jadhavarjun** [comment] 2024-06-19 12:21
Hi @Lukas742 ,

Please find the link to Storybook below. It contains a reproducible example of the issue.

Storybook Link: https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-variantmanagement--default&args=placement:Right&globals=viewport:mobile1

I am also attaching a screenshot of storybook in which when we are viewing in mobile view with width 320 pixel then the **Save** and **Manage** buttons are getting truncated.

<img width="337" alt="save and manage button truncate" src="https://github.com/SAP/ui5-webcomponents-react/assets/66779051/fa9e7c12-743f-491f-a3cb-21ced4a6eb8a">

**Comment by Lukas742** [comment] 2024-06-19 14:11
Hi @sanjayC5373903 

The `ResponsivePopover` used as the popover for the `VariantManagement` utilizes the user-agent, among other factors, to determine whether the popup should be rendered as a `Dialog` (mobile) or as a Popover. Since this is not checked in runtime, but only on initial render you'll still see the `Popover` if you didn't refresh the page.  Opposite to the dev-tool's device view, Storybook doesn't change the user-agent, so even though the viewport is rendered with `320px`, it's not recognized as mobile and therefore a `Popover` is still displayed. 
If used on a mobile device, a `Dialog` is displayed and all buttons are fully visible:

![image](https://github.com/SAP/ui5-webcomponents-react/assets/9749730/6b21e4e3-7f07-4999-945b-7a0061ba3a1d)

I'm going to close this issue now, as the component is working as intended. In case of further questions or additional feedback, please feel free to leave another message here. We're also monitoring closed issues :wink:

**Closed by Lukas742** 2024-06-19 14:11 UTC
Labels: bug, author action
