### ISSUE TITLE
[Page]: [Page component does not render footer correct in v2]

### ISSUE THREAD

**Issue by sdommel** [SAP/ui5-webcomponents-react#6491] opened 2024-10-14 14:01 UTC
### Describe the bug

We are updating to v2. 
We noticed the Page component does not render the footer correctly anymore. 
It seems to be the case in the manual as well: https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/layouts-floorplans-page--docs 
However in the manual of the web components it seems to work: https://sap.github.io/ui5-webcomponents/components/fiori/Page/

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/layouts-floorplans-page--docs 

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

Footer is displayed on bottom of the component

### UI5 Web Components for React Version

2.2.

### UI5 Web Components Version

2.3.

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-10-14 15:17
Hi @sdommel after some investigation it turns out that this bug is known in the ui5-webcomponents repo and also already fixed, but not released yet. 
I'll close this issue here, but if you have any questions or additional feedback feel free to post them in the linked issue.

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/9981

**Closed** 2024-10-14 15:17 UTC
Labels: bug
