### ISSUE TITLE
Page: Footer is displayed on top of page

### ISSUE THREAD

**Issue by tkeiner** [SAP/ui5-webcomponents-react#6580] opened 2024-11-01 12:05 UTC
### Describe the bug

This bug can even be found in the documentation:
https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/layouts-floorplans-page--docs

The ui5-page component does not have this issue:
https://sap.github.io/ui5-webcomponents/components/fiori/Page/

### UI5 Web Components for React Version

2.3.3

### UI5 Web Components Version

2.3.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-11-01 14:37
Hi @tkeiner 

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/9981).

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/9981

**Closed by Lukas742** 2024-11-01 14:37 UTC
Labels: bug
