### ISSUE TITLE
[Dialog]: Dialog will close when Select is used

### ISSUE THREAD

**Issue by skowrons** [SAP/ui5-webcomponents-react#6416] opened 2024-09-28 13:39 UTC
### Describe the bug

We have multiple forms that are contained within a dialog component. Each time we use any `Select` component in our form the dialog will close when the user selects anything.

### Isolated Example

https://stackblitz.com/edit/github-hwdhng?file=src%2FApp.tsx

### Reproduction steps

1. Click open
2. Select some option
3. Dialog will close

### Expected Behaviour

Dialog should not be closed when using a `Select` component inside its body.

### UI5 Web Components for React Version

2.1.1

### UI5 Web Components Version

2.2.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-09-30 06:15
Hi @skowrons 

I will close this issue as there is already [another one](https://github.com/SAP/ui5-webcomponents/issues/9484) covering this topic. If you have any questions or more information, please address them in the original issue.

To prevent this behavior, you can stop the `close` event of the `Select` component from bubbling by calling `event.stopPropagation` in the respective handler. ([StackBlitz example](https://stackblitz.com/edit/github-hwdhng-oxbhpt?file=src%2FApp.tsx))

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/9484

**Closed by Lukas742** 2024-09-30 06:15 UTC
Labels: bug
