### ISSUE TITLE
Icons Library: Icons do not render

### ISSUE THREAD

**Issue by I347684** [SAP/ui5-webcomponents-react#3880] opened 2022-12-15 11:38 UTC
**Describe the bug**
I'm using typescript. I tried:

import '@ui5/webcomponents-icons/dist/AllIcons' - Using this I only get the icon "employee" in all of my Avatar or Icon components. If at runtime I change the name of the icon, it will show. If I refresh, the "employee" is rendered again.

![image](https://user-images.githubusercontent.com/35697392/207849207-b2694266-fdff-4bf7-a99d-d16c7b670d65.png)

Correct icon name in component
![image](https://user-images.githubusercontent.com/35697392/207849264-fbab4dca-9941-4ca8-8681-ecd5943b0417.png)

Change icon name at runtime changes the icon from employee to the actual icon

![image](https://user-images.githubusercontent.com/35697392/207849300-78e06307-aa89-4195-96fe-8c1ed62944c9.png)

I tried to import one icon at the time as suggested in the documentation like this, in a component where the icon is used

import '@ui5/webcomponents-icons/dist/circle-task'

and I have this error in the console, and no icons are loaded. 

```No loader registered for the SAP-icons-v5 icons collection. Probably you forgot to import the "AllIcons.js" module for the respective package. ```

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "^1.9.2",
    "@ui5/webcomponents-base": "^1.9.1",
    "@ui5/webcomponents-fiori": "^1.9.2",
    "@ui5/webcomponents-icons": "^1.9.1",
    "@ui5/webcomponents-icons-business-suite": "^1.9.2",
    "@ui5/webcomponents-icons-tnt": "^1.9.2",
    "@ui5/webcomponents-react": "^1.6.0",
    "@ui5/webcomponents-react-base": "^1.6.0",
    "@ui5/webcomponents-theme-base": "^1.0.0-rc.16",
    "@ui5/webcomponents-theming": "^1.9.1",
    
Operating System:
Browser: Chrome

**Comment by Lukas742** [comment] 2022-12-15 11:51
Hi @I347684 

This issue is a duplicate of https://github.com/SAP/ui5-webcomponents/issues/6043 and a fix has already been merged but not released. If you have any questions or more information, please address them in the original issue.

Until the fix is released you can use a workaround by setting the `initials` (e.g. `initials="EG"`)

**Closed by Lukas742** 2022-12-15 11:51 UTC
Labels: bug
