### ISSUE TITLE
[Toolbar]: [Unable to open popover by ToolbarButton]

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents-react#6561] opened 2024-10-28 07:25 UTC
### Describe the bug

Hi team, we are upgrading ui5 webcomponents to 2.x and here's an issue we find on Toolbar component. Clicking toolbar button does not trigger popover's appearance. https://github.com/SAP/ui5-webcomponents/issues/9997 might be the relevant issue.

### Isolated Example

https://stackblitz.com/edit/github-vzyekk?file=src%2FApp.tsx

### Reproduction steps

1. Open https://stackblitz.com/edit/github-vzyekk?file=src%2FApp.tsx
2. Click "Open Popover" toolbar button
3. Observe that the popover does not appear

### Expected Behaviour

The popover should appear nearby the "Open Popover" toolbar button

### UI5 Web Components for React Version

2.3.2

### UI5 Web Components Version

2.3.0

### Browser

Chrome

### Operating System

macOS 15.0.1

### Organization

SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-10-28 08:27
Hi @2bno1 

you're correct, https://github.com/SAP/ui5-webcomponents/issues/9997 is describing the same issue, so I'm closing this one as a duplicate. In case of additional questions or more information, please address them in the original issue.

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/9997

**Closed by Lukas742** 2024-10-28 08:27 UTC
Labels: bug
