### ISSUE TITLE
[SF_ACC][DynamicPageTitle]: Button not working by clicking enter key or space key in DynamicPageTitle

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents-react#4217] opened 2023-02-27 05:42 UTC
### Describe the bug

If you are using enter key or space key to click the button which was defined in DynamicPageTitle, it won't trigger button onClick event. But if you are using mouse to click the button, it will trigger button onClick event.

### Isolated Example

https://codesandbox.io/s/exciting-andras-lcju89?file=/src/App.js

### Reproduction steps

1. using tab key focus on "Edit" button, then clicking enter key or space key, check the console log there is no "button clicked!" log.
2. using tab key focus on "Click Me" button, then clicking enter key or space key, check the console log there is "button clicked!" log 

### UI5 Web Components for React Version

1.8.1

### UI5 Web Components Version

1.10.5

### Browser

Chrome, Edge, Firefox, Safari

**Comment by Lukas742** [comment] 2023-02-27 07:27
Hi @GongRichard 

this issue has the same root cause as #4190, so I'm going to close this one here. If you have any questions or more information, please address them in the original issue.

Duplicate #4190

**Closed by Lukas742** 2023-02-27 07:27 UTC
Labels: bug
