### ISSUE TITLE
ObjectPage: Header button not working with RTL

### ISSUE THREAD

**Issue by lpohren** [SAP/ui5-webcomponents-react#366] opened 2020-03-20 15:08 UTC
**Describe the bug**
On the Object header, whenever we have a button in the header, RTL is not applied on it.

**To Reproduce**
1. set `dir="rtl"` on the root element
2. Open an Object page that contains a button in the header
3. The button is still left oriented

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16123699/77176448-e526e880-6aa2-11ea-8b5d-9f6af2c33ea0.png)

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version: 0.9.0-rc.1

**Additional comments**
For the element in the image above, a possible solution is changing:
`float: right;
right: 1.25rem`

for

`float: left;
left: 1.25rem`

**Comment by MarcusNotheis** [comment] 2020-03-23 16:45
Hi @lpohren  - just released in version `0.9.0-rc.2`

**Comment by lpohren** [comment] 2020-03-27 16:25
Hi Marcus, 
I tested it on 0.9.0-rc.3 and its still not working. I believe the issue is in the right property which should be set to `none`.
![image](https://user-images.githubusercontent.com/16123699/77777488-685db680-702e-11ea-9861-4360e1f20438.png)

**Closed** 2020-03-31 11:27 UTC
Labels: bug

**Comment by MarcusNotheis** [comment] 2020-03-31 11:33
Hi @lpohren I found the root cause for this Issue. Our Custom Components expect to have a `dir="rtl"` attribute on any parent attribute, that's why the button was on the wrong side. UI5 Web Components for React is now automatically adding this `dir` attribute to the `html` tag when UI5 Web Components are detecting an `rtl` environment.
Released again in `0.9.0-rc.7`
