### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents-react#2127] opened 2021-09-15 12:22 UTC
**Describe the bug**
At RBSC we spotted a critical memory leak in our application. The memory leak is related to unmounted DOM elements which are not garbage collected. I am not sure if the main issue is related to the web-components or something else and I would appreciate your help.

**Isolated Example**
[Sandbox](https://codesandbox.io/s/clever-moon-opjpw?file=/src/App.js)

**To Reproduce**
1. Go to the sandbox
2. Click on both `Data 1` and `Data 2` multiple times
3. Observe the Performance Monitor in Chrome/Edge
4. The number of DOM Nodes increases and it is never garbage collected

**Expected behavior**
I would expect the number of nodes to decrease after a navigation is done

**Screenshots**

The number of nodes that the application uses initially
![image](https://user-images.githubusercontent.com/21200806/133427969-d95e96c3-dba5-4840-ac13-2f90b2ac6b5a.png)

And how they increase and are not garbage collected.
![image](https://user-images.githubusercontent.com/21200806/133428112-db482eac-8490-40cd-a0a0-e355050b66e8.png)

**UI5 Web Components for React Information**
"@ui5/webcomponents": "latest",
"@ui5/webcomponents-fiori": "latest",
"@ui5/webcomponents-react": "latest",

Happens on Safari, Chrome/Edge on both MacOS and Windows 10.

My personal setup
Operating System: Windows 10
Browser: Microsoft Edge, Version 93.0.961.47 (Official build) (64-bit)

**Additional context**
I managed to reproduce the memory leak, by extracting both `PageA` and `PageB` is separate files. If I leave only the `List` components in the pages I can see the DOM nodes being garbage collected. The issue might be related to the `FlexibleColumnLayout` and/or the `DynamicPage`

Your help is much appreciated

**Comment by Lukas742** [comment] 2021-09-16 10:17
Hi @AndrianStoikov

thanks a lot for creating this issue and for the detailed description. It helped me tremendously to narrow down the root cause of this leak. I created a [PR](https://github.com/SAP/ui5-webcomponents/pull/3941) in the UI5 Web Components repo, since the root cause is coming from there.

**Comment by AndrianStoikov** [comment] 2021-09-16 10:39
Hi @Lukas742,

Thank you for the fast reaction and I am glad that I could help you.

Best,
Andrian

**Comment by AndrianStoikov** [comment] 2021-09-27 06:24
Hi @Lukas742,

I see that we are still waiting the web-components team to review the PR. Since this is a critical issue is it possible to coordinate it with them and have it merged soon? As I understand they will be releasing rc.16 soon so I think it is important to have this merged asap.

Best regards,
Andrian

**Comment by Lukas742** [comment] 2021-09-28 13:05
Hi @AndrianStoikov 

https://github.com/SAP/ui5-webcomponents/pull/3941 just got merged, so it will be available with the next release candidate :) 

Thanks @pskelin and @vladitasev for the support!

**Comment by MarcusNotheis** [comment] 2021-10-08 08:32
We released this fix a snapshot version: `0.0.0-e5a9d54a`.
Please use in combination with `@ui5/webcomponents@0.0.0-11d529e8a`.

**Closed by MarcusNotheis** 2021-10-08 08:32 UTC
Labels: bug, ui5-webcomponents
