### ISSUE TITLE
[Object Page / Modals]: Modal container not defaulting correctly when Objectpage is present

### ISSUE THREAD

**Issue by gitgdako** [SAP/ui5-webcomponents-react#6621] opened 2024-11-14 11:20 UTC
### Describe the bug

I am well aware that this will most probably be hard to solve for you, but I would like to just make you aware of the issue we are experiencing

I have not started defaulting our whole configuration but have limited the frontend code to
```
import {Button, Modals, ObjectPage} from '@ui5/webcomponents-react';

function main() {
  createRoot(document.body).render(
    <>
      <Modals />
      <Button onClick={() => Modals.showToast({children: 'test 1'})}>Test 1</Button>
      <Button onClick={() => Modals.showToast({children: 'test 2'}, document.body)}>Test 2</Button>
      <ObjectPage />
    </>,
  );
}
```

According to https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/user-feedback-modals--docs these should be the same as container should default to document.body

Rendering this and nothing else the second button always works but the first button only works if I remove the ObjectPage component. It works fine in our storybook as well as your stackblitz. 

We have had the issue since upgrading to 2.0, but only tried the fix in 2.4. Using the paramerized call is a valid workaround for us for now.

Hoping for any ideas...

### UI5 Web Components for React Version

2.4

### UI5 Web Components Version

2.4

### Browser

Chrome

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment] 2024-11-15 07:20
Hi @gitgdako 

the root cause is the same as explained in [this issue](https://github.com/SAP/ui5-webcomponents/issues/10158), so I'm closing this one as duplicate. If you have any questions or more information, please address them in the original issue.

Duplicate of https://github.com/SAP/ui5-webcomponents/issues/10158

**Closed by Lukas742** 2024-11-15 07:20 UTC
Labels: bug
