### ISSUE TITLE
[Component Name]:

### ISSUE THREAD

**Issue by srinivasManduva** [SAP/ui5-webcomponents-react#4713] opened 2023-06-11 07:40 UTC
### Describe the bug

Analytical Table inside a dialog dosen't reset itself after closing the dialog

https://codesandbox.io/s/vigorous-davinci-c9vgrm?file=/src/App.tsx

### Isolated Example

https://codesandbox.io/s/vigorous-davinci-c9vgrm?file=/src/App.tsx

### Reproduction steps

1.open the sandbox provided
2.open the dialog
3.either toggle the button or expand the rows or both
4, close and reopen the dialog
5, the dialog should reset to the original state but it dosent
...

### Expected Behaviour

when the dialog is closed the table is expected to go back to the original state i.e. all rows un expanded but that dosent happen and the table remembers the previous state i.e. if the first row is expanded when reopened its rendered with only the 1st row expanded

### UI5 Web Components for React Version

1/5/0

### UI5 Web Components Version

1.9.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by srinivasManduva** [comment] 2023-06-12 03:17
Hi Team, 
and also if we close the dialog with esc button we are unable to open it once again this is also reproducible in the above mentioned sandbox

thanks,
Srinivas

**Comment by Lukas742** [comment] 2023-06-12 06:13
Hi @srinivasManduva 

Please follow the guidelines for opening issues. "[Component Name]:" doesn't give information of the affected component and neither of what the issue is about.

You codeSandbox example is showing multiple issues with your implementation and none of them are related to UI5 Web Components for React.

- How should the AnalyticalTable reset itself if you don't implement a behavior for that? Since it stays mounted, the internal state never resets so it's the expected behavior to have the same state.
- You're using multiple `ThemeProviders`, even though this shouldn't affect the implementation it's still considered bad practice at it only adds overhead and no additional functionality.
- You don't reset the React state of the Dialog when closing it via esc, so the state will still be `true` and therefore doesn't update. In React it's always recommended to fully control the component.

**Closed by Lukas742** 2023-06-12 06:13 UTC
Labels: bug
