### ISSUE TITLE
Variant Management: missing accessibility props

### ISSUE THREAD

**Issue by sparkypro** [SAP/ui5-webcomponents-react#3123] opened 2022-06-24 07:06 UTC
**Describe the bug**
Accessible name properties missing for VariantManagement UI component

**UI Link**
Refer: https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-variantmanagement--default-story

**Missing**
Accessible name property is missing for VariantManagment UI, component. 

**Expected behavior**
Accessible name property must be available. 
Also provide accessible reading for selected value if any.
This property enables the accessibility options for screen readers. 

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.0
`@ui5/webcomponents-react` version: 0.25.6
Operating System: Windows 11
Browser: Chrome

**Comment by Lukas742** [comment] 2022-06-27 07:43
Hi @sparkypro 

I don't see why we would need an `accessibleName` prop here. Could you elaborate more on why you think this is necessary.

**Comment by sparkypro** [comment] 2022-06-27 07:52
On screen reader like JAWS, the dropdown arrow applicable shall read 'Select View' twice. This is because, inside 'VariateManagement' component, there is a ui5 button (which is a dropdown arrow) which has property set as 'Select View' for both title & aria-label. Both has same value, which is internally applied, and have no control to developer to change the aria-label. Because of this the screen-reader picks up both title & aria-label which is read to user which is confusing.

**Comment by sparkypro** [comment] 2022-07-13 09:53
Also additionally a tooltip is also required as part of the dropdown select view.
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANAAAABFCAYAAAA7D2iEAAAQrklEQVR4Ae1djW8U1Rb3/yBAUDCIFBEEtA+q8Cr2NbECWotiqY8++uwTnjXYRs0GX2j8oNrwUlkFkYAkPiBRNmKzSKAGJKV+tFWkCraIbYXdttvtsl1Kd7fb/l7O7Mx0ZnqnuzO73bLTe5Ob+br33HvOPb/7ce7H3AHuuAS4BExL4A7TMXlELgEuAXAAcSVIPwkMD2Okvx+RP/9E+NdfEfruOwTPnEHw9GkMnjyJwRMnMPjllwhfvIjhvr4J5Y8DaELFm97Eh71eDLW2Cgoa+v57QSGHrlxB5Pp1DPt8ghJTmIjbjUhHB4ba2hBuaUH4xx+jSn3uHIJff43Br77C4PHjuPX55xg4fBgDhw7h5v79CNjt6K+uRv+bb8K/fTtulJejb+tWeDdvhve559D75JPw5Oaie9UqdD34INwLFsB9551wTZtmyHufeQaBmhqEGhqSXiAcQEkXaXoSJEAE3n8/qrBLlhhSUKMKPZnhfS+/jKHLl5NWSBxASRNl+hIKNzfDk51tWdBoAds1dy6CdXVJKTAOoKSIMX2JRFwuoXukVbKp8Bxpb0+44DiAEhZhehOg8cdUAAuLRxp3Jeo4gBKVYJrH73nkkfQD0IwZ6Jo3Dz3Ll8Pz+OPwFhbC9+KL8L30Em5s2yYYI2689hp6Vq6MyRtZ8xJxHECJSC/N444MDIyrYF333QfP6tXwPvssvBs3Rq1iOTmC4nYtXCgocffixejOzETPqlWCAaJ33TqQ1ctbVIS+zZvh27IFN155BaTQ/jfeQP9bb6H/vfcEq9jNPXswcPCgYJm75XBg0OkUTNHBc+cQ+uEHhH/+GUO//SZY+Ia7uwWr30g4bEjqZBkkyx+rBaJ3ZDhJxHEAJSK9NI8bamxkKpZ3wwYYVdTbXRT9777L5LX3qacSyjoHUELiS+/IVNOzamZqOazmaP6KxSu9o3kss44DyKzkLBAvePYsU6n6XnjBAtyNZcGTk8Pkl7qPZh0HkFnJWSBe6NtvmQrVt2mTBbgby0L/O+8w+aUxmlnHAWRWchaIR2vIWN2avueftwB3Y1mg9XIsfslYYtZxAJmVnAXikaWLpVBkcbOkGxqCa+ZMJs9DV6+aYpkDyJTYrBFJ1wpXWGgNBhlckIWRVWkEv/mGETr2Kw6g2DKybAhaA8dSJpr3sarz22xMnmmuyIzjADIjNYvEmYoAuvnhh0wA0eSuGccBZEZqFokT/uknpjLRSgKrOtqXxGp1aRmQGccBZEZqFokTvnCBqUzeggImh5HhYQzcGoTPH0Bv3w309PZNmCf6lA6lR+kmy+m1ur15eaaS4AAyJTZrRKK1ZqzauDc/X8XgyMgI+m8OwOP1obfPhx4PAcc3YeCJAjOaDqVH6VL6lI9EHa2pY/FMa/vMOA4gM1KzSBw6M4ClTMr1YeHwELy+G+j1TjRgxm/NCESUD8pPQm5khMkzycHM+j8OoIRKI70j0/kFTACtWycwRspKrYFnwlub8cEjdRWlfCQKou6lS5l80+ZCo44DyKjELBQ+/MsvTEWiLQnUXaIaX1JaSYkn+0r5oXwl0p2jPUSsioMqFKOOA8ioxCwUng7XYClS7xNPCGOOye626YFVGhOZLYq+4mIm32YmUzmAzJaCBeLpAciTlycM3PUU+HZ4TyAya527UVHBBNCtL74wXKocQIZFZi5CY3UWpmdkYXq18W6CuRRjx6LdnqwWqDs3N2ptm0AzdaIgJOscmbjNuP6dO5l8Dxw4YJjcpADIf7UBhyttKMhfg0WkVOSXrUHBehsqjzagM7Ft6oaFkIoItyWAWluZitRF27YFU3V8g/tEwWAqvqdPmCcyU3Y3P/6YyXegutowudQCKOJFfVXxKGgk8Givy4pR6WhHUMvOhSNR0JXWokf77TZ/vi0BpLNL0716dQrmeRIFJ81J3TBV6nRCKqvlpXVyRl1KAdTjqIi2NhlZyCw5BGdzO3p8AfjJd7SizmFHyQqxRcrIhe20V81Psz0anwNILReTT0O//85UJHf2oxM8SZooeEbjm2GdjhtmAcjMPqgUAqgVex+LgiOnqmls6yJJIuJFXVUpyh0MmzwHkCSlpFxpDwxLkdyr/mppAOmO/TIzDcs1hQBqQY3YVbOdCRnLaFctSrTdPPnZjkYNNRpjHXy9DAXZ2WKLl4s1JTtw8Ew7/BFNYHqU6e9CPfUbB9rhrLap45fZ4bwUYEQWX0UCaHPaUa4Y12Xm2VDjaBHSjNWF62muRU1ZMdZILTCNCcvscDRrWmEpB1JlUlyLToTQ5tiFIpFf22lNPruaBHkoaRe9fgTnzrexAbRylaUBRCsOWBUHvTN6TtykAChnT6ukBvFdZQWXunfKqwJAERfq/jP+GCtz2yl0akEk06+Ao60FNXlK+sr7QtQ0M8A/0Iq9GyWwKsNH7xdtqYWjSnyvtcINtOJgSa7ctRUMKnLlQHGyUbC7ZWyLLQEoww6Ho0I1rqxpHhVr58mdWKOiN5q/ZfOeYivSww+bBtBvv/8B5+mzaP/TFZPG2fPf44+OazHDjWdkGOXU2B2dY8cCES1vMuJSCKAQ6t+WlCwX5Udb2a3BOLmXx1DMMVAIjdWSIhai/EATOgdEYpEAWhyjilR0VNM9lAFUjKIN2ViUvxOHm13RsZnPi7Yz+1C0TFS8DcfQqcpjAHUVIl+C8aMVfsn6MeBC/Z4yZGZkY5EUXwUgFxwlIt1lpahyKuIGXajfXSoCIxtV5zXAlQEUpS2MKc83of58E9p8YgYvHZLBQ9/rO0QakRD8LbX47+NZTCVyJQCg8jd2CpXBI3nP4ceLv+qC4+9bXxXCrS38l26Y8YAjfVMVhYEHOnmIBSA63NGISyGAqGukrd1zsaZsFw47W9HZr1EQBhfjAwhAxAVnxQ4cbmPTatlTEK3p12tAIAMoC9Pz7GiUgKfIg99pE1uJCjg9ig+XDiFHqOGzUXmOnW7nZ6PGkzHzQCSTLXbUK2nK5ANwbhMBVtmgboVkAGVhemnt2FYVBGwF6LWtLomr9QRTidwrVphW6ld3vCvKKQt/yy/G5bY/xtCSwEOtLd1LYDBzlUVl8EZvLujmBx8YopRaAFHW+lvhqCxFJqNbsSi7FLYDDaM1qIaVmADShB/z+J1oxctQdPsokAJAJQ6dMcd1aRxWgL2XRim37BNB+dgh6E6RBhtQKfGraoFG6ejddX5WFlVIbaurABATuP1nYRPTtJ3UjInExCLXrrEBtHx5QkqtBAi1MB3X3DI95bfn/vkKXN0e+VsqAaR33C+tUjDiUg8gKXc06D5fi4M0oSoP9sUak/r9VQ1jungJA0hWOn0AKccPUlaFqwJko2EUtXxVkyq4+sELR6nIm0EA6fIs81IGx3V1asKT3DLqfBcabBcbQA9lJqTUBAQlUJ75x8sCPeW7/E3/jmucFAtUDM7jehU6f57Ju3IrRzyEJg9AmtwFPe2od9ixVQGmNfvUxgZdZVLSinjR6DiCSqVFS6r95WuyABQ/MBr1jAiU9/521B21w1ZSjJXSWEnOqwg83RaoAo4upQDEexlgOt8JQG43U4ncSQCQFkRK8DyxoRStV9oTBimlYdbptb5d8+cbInnbAEjOdcQFxxbJ2CCalcWPsQAUbN6HAq0CrihEwfriqM+TjAypBpCipdK0QJ3HbWO6s4uyxfxSvqUKZQIApLc707V0WVKUWwsiGvPk5G9Cy+UrSaMv642JG/fcucwKZNjDHJAyU7j9AETZvLBPtD6pa89xARRsQpUInkX5djivehHUDpzlWjl5AHJuEVuIcbtwLjiKGV24jmMoEluazG1H0NgRGJNnXZ5lXtQykktZlqF+F264p4epQK6lS5Om4EoQkWWu+Wd9yxyFNeplfk3c0A+MWZY42uoer7s9AST339XKoatMxK2sUMU4rHPIZPDcLtFClCwAASojghawUin4TqFc6pIpWiCZnwx1SytFo2vnp8UxjAhqGclxFUaEcifbiEA1LUuB3A88YFiRYyl+vHNDsehov8v8mrjRNWWfPBk3tdQBiIwGR3egqKoBPXqKRtmOBFBfJVq2ltnRqAgrK5zWDE3xZABpzMySKFRdw+QBiNKNrijXM2PT/FShbNpVmrFlfpbtY1vwlGZ/o104KMZnNHelkKMkkuGL/2MDaPHipANIq/jJepZ4MXP1V1Yy+R/45JO4yaUMQP6TO0Zny1eUwra7FnWaxaT1ziMoz5fGP9nYelxtUiYa0Zn6Uuxt9oqLUL3wE7sKK9matxsUk6gh0NKevarZ/iQCSKmo4kRqjy+EYJAWyLbgsHZlhKIFUoJv66eKSdRICJ3Nx1ApyyI616Naga6oMJhGBADBZrs4RxVdvFvfEYA/GEJQmBw+hJcy/8JUIPf9908JAN3cv5/JP/3FIV6XMgBRhjqdO8cO8qWujepKKxUY2xkUIBld8iJ1fzQ1vYoe7TcqxV7nEXFNXTIBBOD6KZRLa9i06WZkQXcpj6pVFMdIyvh5O1H3mc4K9DgABITQuFt/adO989czFci9cOGUABCtOmB1YX1bt8aLH6QUQEKuIl60OI8JZmbZwkRKo9hQJy9FYbDhv3AMto3SRrxsrMzfiTrZaBIas6CTLFrl1afQRpv0ZABqunny+yyMzvFoEo8VhkzRB3agRLb0Ud5sqKHlORGgZbfYsipbIEqCzO6qeFnIzCuD7UBTtKsrAUXbzZPeZ+iMgRTZlxaqyibyFYUoef0IGtr8TAVyLbjP0vuBJNHoHrK4dq0UJOY19QCKmSUeIFUSoJXHrBrYvWCBpXekSvLVmwczcsgiB5AkzSl41QXQvfda+kwEZVHr/S8o3m0NHEBKaU6x+5FAgNkCdc2bZ+lTeZTFrLetIdLergyme88BpCsa638YuXWLCSCaoZfOwk6WuTmZdOi8OspfMpzn0UeZMuAASoZ0LU5jPABZ+WRSZbFyACmlwe8NSWAkFGLWvu45cwQ6Vj0bWykkz+rVTBnE+89U3oVTSnOK3eudDeCePVuWBIFIOCN7kv/OQN22pPydQeYsesMBpBEIfzQgAfpr9bRpY7x71iwVEerOSWOidP8/kIoxABxAWonw5/glEImMAY8AqJkzmTSs8Ic6LWMcQFqJ8Of4JTA8zAbQjBnx00jzkBxAaV6Ak5p9vb+1TZ8+qdlKZeKenBxmJcKNCKkshTROyzV9OlOB6OdbQ21tiHR0gP7cRnuHaHZ+XB8IgCZnVX5gACNaf+sWyIQelx8cxIjWh0IgC6LKh8PCLxrJMBLLY2gI5PX+0EfdWNpsGI/jVrh4pGSxMASCwRMn4N++Ha4ZM5gAYhkXpsq77oceirvEOYDiFpU1Agbsdg4YhuVRWTnQmXHxOg6geCVlgXD9VVUcPDHAQ0AKN413RJlaETiA1PKw9FPP8uUcQDEA1Ld5syEd4AAyJK70DqxnslV2X6byvW/LFgz7pIPF4ytrDqD45GSJUIGaGt0WiDaRebKz0fv00/AWFKB37VrQsU+03J9aru4lS9C1YMGonz8fdAihys+bB9oKofL33IMujafV3nH7u++GW+vnzAGt11P52bNBS5BU/q674Gb5WbNAqy2oQvEWFuLmRx8hfOGCqTLmADIltvSNRGdC02/syZMVjqxx8W4eS1+uJy7nHEATJ1tOeQpIgANoChQyZ3HiJMABNHGy5ZSngAQ4gKZAIXMWJ04C/wdfdFODpKGAeQAAAABJRU5ErkJggg==" alt="image">

**Comment by Lukas742** [comment] 2022-11-08 12:53
Hi @sparkypro 

when the linked PR is merged and released a tooltip will now be displayed when hovering the dropdown button, and the `aria-label` will be added to the right place inside the shadow root. If JAWS still reads both the `title` and the `aria-label`, then this should be the intended behavior, as we need both attributes here for accessibility reason.
Since this behavior should not be changed, we won't offer a way to customize it.

**Closed** 2022-11-08 15:38 UTC
Labels: bug, a11y
